version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Containerfile
      tags:
        - "bd-reto-1:latest"
    container_name: contenedor-bd-reto-1
    networks:
      - reto-1
    ports:
      - "8000:8000"
    hostname: db
  client:
    depends_on:
      - server
    build:
      context: ./client
      dockerfile: Containerfile
      tags:
        - "cliente-reto-1:latest"
    container_name: contenedor-cliente-reto-1
    networks:
      - reto-1
    hostname: cliente

networks:
  reto-1: {}
