FROM docker.io/debian:12-slim

RUN apt update && apt install -y git curl

RUN git clone https://github.com/dpkg-i-foo-deb/microservices

WORKDIR /microservices/taller-2/reto-1/

RUN chmod +x client/script.sh

RUN curl -sSf https://install.surrealdb.com | sh

CMD [ "/microservices/taller-2/reto-1/client/script.sh" ]