version: '3.8'

services:
  db:
    build:
      context: ./server
      dockerfile: Containerfile
      tags:
        - "db-reto-2:latest"
    environment:
      POSTGRES_USER: dpkg
      POSTGRES_PASSWORD: dpkg
      POSTGRES_DB: auth

    container_name: db

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U dpkg -d auth" ]
      interval: 5s
      timeout: 5s
      retries: 5

    ports: 5432:5432
    networks:
      - reto-2

  client:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: ./client
      dockerfile: Containerfile
      tags:
        - "cliente-reto-2:latest"
    container_name: contenedor-cliente-reto-2
    networks:
      - reto-2
    hostname: cliente

    environment:
      - CONNECTION_STRING=postgres://dpkg:dpkg@db/auth

networks:
  reto-2: {}
