version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: dpkg
      POSTGRES_PASSWORD: dpkg
      POSTGRES_DB: auth

    container_name: db

    ports: 5432:5432
    volumes:
      - ../server/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - reto-1

networks:
  reto-1: {}
