version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: dpkg
      POSTGRES_PASSWORD: dpkg
      POSTGRES_DB: auth

    container_name: db

    ports: 5432:5432
    volumes:
      - ../server/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - reto-2

  client:
    depends_on:
      - db
    build:
      context: ./client
      dockerfile: Containerfile
      tags:
        - "cliente-reto-2:latest"
    container_name: contenedor-cliente-reto-2
    networks:
      - reto-2
    hostname: cliente

    environment:
      - CONNECTION_STRING=postgres://dpkg:dpkg@db-reto-2/auth

networks:
  reto-2: {}
