[package]
name = "auth_bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
auth_http = { path = "../auth_http" }
rocket = { version = "0.5.0-rc.3", features = ["json"] }
