FROM docker.io/rust:alpine as build

RUN apk add git musl-dev

RUN mkdir /workspace/

WORKDIR /workspace/

RUN git clone https://github.com/dpkg-i-foo-deb/microservices

RUN cd microservices/taller-1/reto-5/servidor && cargo build --release 

FROM docker.io/alpine:latest as prod

ENV ROCKET_PORT=80
ENV ROCKET_ADDRESS=0.0.0.0
ENV SECRET="uwu"

EXPOSE 80/tcp   

COPY --from=build /workspace/microservices/taller-1/reto-5/servidor/target/release/servidor /bin/server

CMD ["server"]