FROM docker.io/rust:bookworm as build

RUN mkdir /workspace/

WORKDIR /workspace/

RUN git clone https://github.com/dpkg-i-foo-deb/microservices

RUN cd microservices/taller-2/reto-2/client && cargo build --release 

FROM docker.io/debian:12-slim as prod

COPY --from=build /workspace/microservices/taller-2/reto-2/client/target/release/auth /bin/client

CMD ["client"]