FROM docker.io/debian:12-slim

RUN apt update && apt install -y curl git

RUN curl -sSf https://install.surrealdb.com | sh

RUN git clone https://github.com/dpkg-i-foo-deb/microservices

WORKDIR /microservices/taller-2/reto-1/

RUN mkdir database

RUN chmod +x server/script.sh

EXPOSE 8000

CMD [ "server/script.sh" ]